<?php
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}
function awp_wc_get_default_options() {
    $default_options = array(
        "algo_wc_quick_heading_1" => "",
        "algo_wc_enable_quick_view" => "1",
        "algo_wc_enable_quick_view_mobile" => "1",
        "algo_wc_quick_heading_2" => "",
        "algo_wc_enable_lightbox" => "1",
        "algo_wc_enable_flexslider" => "",
        "algo_wc_quick_view_navigation" => "1",
        "algo_wc_quick_heading_3" => "",
        "algo_wc_quick_view_mode" => "popup",
        "algo_wc_select_modal_effect" => "fade_in",
        "algo_wc_modal_width" => "1000",
        "algo_wc_modal_height" => "600",
        "algo_wc_quick_heading_4" => "",
        "algo_wc_quick_view_button_type" => "use_button_icon",
        "algo_wc_quick_view_button_label" => "Quick View",
        "algo_wc_quick_view_button_icon" => "",
        "algo_wc_quick_view_button_position" => "after_cart_btn",
        "algo_wc_quick_heading_5" => "",
        "algo_wc_show_product_img" => "1",
        "algo_wc_show_product_name" => "1",
        "algo_wc_show_product_rating" => "1",
        "algo_wc_show_product_price" => "1",
        "algo_wc_show_product_excerpt" => "1",
        "algo_wc_show_product_add_cart" => "1",
        "algo_wc_show_product_meta" => "1",
        "algo_wc_show_full_dec" => "",
        "algo_wc_quick_heading_6" => "",
        "algo_wc_product_img_width" => "400",
        "algo_wc_product_img_height" => "600",
        "algo_wc_quick_heading_7" => "",
        "algo_wc_add_view_detail_btn" => "1",
        "algo_wc_modal_background_color" => "#ffffff",
        "algo_wc_modal_overlay_bg_color" => "#000000",
        "algo_wc_close_btn_color" => "#e20404",
        "algo_wc_quick_view_button_color" => "#eeeeee",
        "algo_wc_quick_view_button_text_color" => "#333333",
        "algo_wc_quick_view_button_hover_color" => "#bebcbc",
        "algo_wc_quick_view_button_hover_text_color" => "#333333",
        "algo_wc_quick_heading_8" => "",
        "algo_wc_main_text_color" => "#333333",
        "algo_wc_star_color" => "#ffe234",
        "algo_wc_quick_heading_9" => "",
        "algo_wc_add_cart_button_color" => "#000000",
        "algo_wc_add_cart_button_text_color" => "#ffffff",
        "algo_wc_add_cart_button_hover_color" => "#2c2d33",
        "algo_wc_add_cart_button_hover_text_color" => "#ffffff",
        "algo_wc_quick_heading_10" => "",
        "algo_wc_view_details_button_color" => "#383838",
        "algo_wc_view_details_button_text_color" => "#ffffff",
        "algo_wc_view_details_button_hover_color" => "#000000",
        "algo_wc_view_details_button_hover_text_color" => "#ffffff",
        "algo_wc_quick_heading_11" => "",
        "algo_wc_awp_wc_nextprev_button_color" => "#515151",
        "algo_wc_awp_wc_nextprev_button_text_color" => "#ffffff",
        "algo_wc_awp_wc_nextprev_button_hover_color" => "#000000",
        "algo_wc_awp_wc_nextprev_button_hover_text_color" => "#ffffff",
        "algo_wc_quick_heading_12" => "",
        "algo_wc_awp_wc_loader_color" => "#000000",
        "algo_wc_custom_css" => ""
    );
    return $default_options;
}
?>